import numpy as np
from architector import build_complex, convert_io_molecule
import os, glob

BASE_DIR = os.path.dirname(os.path.abspath(__file__))

# Delete any old .xyz files before building new ones --- SOS!
for old_file in glob.glob(os.path.join(BASE_DIR, "*_oct.xyz")):
    os.remove(old_file)

def octahedral_complex(metal: str, ligand: str, oxidation_state: int):
    my_input = {
        "core": {
            "metal": metal,
            "coreType": "octahedral",
        },
        #DONT MESS UP THE SMILES NOTATION -- CODE CRASHES OTHERWISE!
        "ligands": [
            {"smiles": ligand, "ligandType": "mono", "coordList": [0]},
            {"smiles": ligand, "ligandType": "mono", "coordList": [0]},
            {"smiles": ligand, "ligandType": "mono", "coordList": [0]},
            {"smiles": ligand, "ligandType": "mono", "coordList": [0]},
            {"smiles": ligand, "ligandType": "mono", "coordList": [0]},
            {"smiles": ligand, "ligandType": "mono", "coordList": [0]},
        ],
        "parameters": {
            "metal_ox": oxidation_state,
            "return_only_1": True,
            "relax": True,
            "full_method": "GFN2-xTB",
        },
    }

    print(f"\nBuilding [{metal}({ligand})6]{oxidation_state}+ ...")
    out = build_complex(my_input)

    key = list(out.keys())[0]
    complex_structure = out[key]
    print(f"Done. Key: {key}")

    return complex_structure, key

def symbols_and_positions(complex_structure):
    moles = convert_io_molecule(complex_structure["mol2string"])
    symbols = moles.ase_atoms.get_chemical_symbols()
    positions = moles.ase_atoms.get_positions()  # (N,3) array, Angstrom units SOS!

    return symbols, positions, moles

def xyz_coordinates(symbols, positions):
    center = positions[0]
    centered_positions = positions - center

    #STACK OVERFLOW --- Builds the table for the coordinates in a good and readable orientation.
    header = f"{'Atom':<4} {'X':>12} {'Y':>12} {'Z':>12}"
    print(header)
    print("-" * 40)

    for sym, pos in zip(symbols, centered_positions):
        print(f"{sym:<4} {pos[0]:12.6f} {pos[1]:12.6f} {pos[2]:12.6f}")

def save_file(symbols, positions, filename):
    """Write a metal-centred XYZ file."""

    center = positions[0]
    centered_positions = positions - center

    with open(filename, "w") as f:
        f.write(f"{len(symbols)}\n")
        f.write("Homoleptic Octahedral Complex - Generated by Architector\n")
        for sym, p in zip(symbols, centered_positions):
            f.write(f"{sym}  {p[0]:.6f}  {p[1]:.6f}  {p[2]:.6f}\n")

    print(f"Saved: {filename}")

def prompt_molecule():
    print("      Homoleptic Octahedral Complex Builder")
    print("\nVALID METALS: Fe, Co, Cr, Mn, Ni, Cu, Zn, Ru, Rh")
    print("\nVALID LIGANDS (brackets [ ] are REQUIRED):")
    print("  [OH2]:  water")
    print("  [NH3]:  ammonia")
    print("  [F-]:   fluoride")
    print("  [Cl-]:  chloride")
    print("  [C-]#[O+]:  carbonyl")

    metal           = input("\nEnter metal symbol: ").strip().capitalize() 
    #Without .capitalize() method, architector can crush if we do not write the name correctly -- SOS!
    
    ligand          = input("Enter ligand: ").strip()
    oxidation_state = int(input("Enter oxidation state: ").strip())

    return metal, ligand, oxidation_state

def main():
    while True:
        metal, ligand, oxidation_state = prompt_molecule()

        try:
            complex_structure, key = octahedral_complex(metal, ligand, oxidation_state)
        except Exception as e:
            print(f"\nError: could not build complex. Common causes: ")
            print(f"\nTechnical detail: {e}")
            again = input("\nTry again? (y/n): ").strip().lower()
            if again != "y":
                break
            continue

        symbols, positions, moles = symbols_and_positions(complex_structure)

        xyz_coordinates(symbols, positions)

        ligand_tag = (ligand.replace("[", "").replace("]", "")
                            .replace("-", "m").replace("+", "p")
                            .replace("#", "").replace("@", ""))
        filename = os.path.join(BASE_DIR, f"{metal}_{ligand_tag}_oct.xyz")
        save_file(symbols, positions, filename)

        again = input("\nBuild another complex? (y/n): ").strip().lower()
        if again != "y":
            print("\nDone. Open visualize.ipynb to view your molecules.")
            break

if __name__ == "__main__":
    main()